### ISSUE TITLE
Deprecated selector in `trailing-spaces/styles/trailing-spaces.less`

### ISSUE THREAD

**Issue by MaximeRDY** [wpillar/atom-trailing-spaces#23] opened 2016-11-10 14:19 UTC
In `trailing-spaces/styles/trailing-spaces.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor:not(.mini)::shadow .lines .line .trailing-whitespace` => `atom-text-editor:not(.mini).editor .lines .line .trailing-whitespace`

* `atom-text-editor:not(.mini)::shadow .lines .line .trailing-whitespace.indent-guide` => `atom-text-editor:not(.mini).editor .lines .line .trailing-whitespace.indent-guide`

* `atom-text-editor:not(.mini)::shadow .lines .line.cursor-line .trailing-whitespace` => `atom-text-editor:not(.mini).editor .lines .line.cursor-line .trailing-whitespace`

* `.trailing-spaces-highlight-cursor-lines atom-text-editor:not(.mini)::shadow .lines .line.cursor-line .trailing-whitespace:not(.indent-guide)` => `.trailing-spaces-highlight-cursor-lines atom-text-editor:not(.mini).editor .lines .line.cursor-line .trailing-whitespace:not(.indent-guide)`

* `.trailing-spaces-highlight-indentation atom-text-editor:not(.mini)::shadow .lines .line:not(.cursor-line) .trailing-whitespace.indent-guide` => `.trailing-spaces-highlight-indentation atom-text-editor:not(.mini).editor .lines .line:not(.cursor-line) .trailing-whitespace.indent-guide`

* `.trailing-spaces-highlight-cursor-lines.trailing-spaces-highlight-indentation atom-text-editor:not(.mini)::shadow .lines .line.cursor-line .trailing-whitespace.indent-guide` => `.trailing-spaces-highlight-cursor-lines.trailing-spaces-highlight-indentation atom-text-editor:not(.mini).editor .lines .line.cursor-line .trailing-whitespace.indent-guide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by kankaristo** [comment] 2016-11-22 06:29
Closing as a duplicate of https://github.com/wpillar/atom-trailing-spaces/issues/22.

This is fixed in https://github.com/wpillar/atom-trailing-spaces/pull/24, but that should only be merged after Atom 1.13 leaves beta, because it would probably break stuff in Atom 1.12.

**Closed by kankaristo** 2016-11-22 06:29 UTC
